/** @type {import('stylelint').Config} */
export default {
  ignoreFiles: ["styles/scss/**/*"],
  extends: ["stylelint-config-standard", "stylelint-config-recommended-scss"],
  plugins: ["stylelint-order"],
  overrides: [
    {
      files: ["*.scss", "**/*.scss"],
      rules: {
        "no-empty-source": null,
        "import-notation": "string",
        "at-rule-empty-line-before": "never",
        "selector-class-pattern": null,
        "keyframes-name-pattern": null,
        "no-descending-specificity": null,
        "no-duplicate-selectors": null,
        "scss/no-global-function-names": null,
        "scss/at-if-no-null": null,
        "scss/at-rule-conditional-no-parentheses": true,
        "scss/at-if-closing-brace-space-after": "always-intermediate",
        "scss/at-else-closing-brace-space-after": "always-intermediate",
        "scss/dollar-variable-colon-space-after": "always-single-line",
        "scss/at-if-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-else-closing-brace-newline-after": "always-last-in-chain",
        "scss/at-else-if-parentheses-space-before": "always",
        "scss/double-slash-comment-whitespace-inside": "always",
        "scss/dollar-variable-empty-line-before": [
          "always",
          {
            except: ["after-dollar-variable", "first-nested"],
            ignore: ["after-comment", "inside-single-line-block"],
          },
        ],
        "scss/double-slash-comment-empty-line-before": [
          "always",
          {
            except: ["first-nested"],
            ignore: ["between-comments", "stylelint-commands"],
          },
        ],
        "scss/at-else-empty-line-before": "never",
        "scss/at-mixin-parentheses-space-before": "never",
        "scss/dollar-variable-colon-space-before": "never",
        "scss/at-function-parentheses-space-before": "never",
        "scss/at-mixin-argumentless-call-parentheses": "never",
        "order/properties-alphabetical-order": null,
        "order/order": [
          [
            "at-rules",
            "custom-properties",
            "dollar-variables",
            "declarations",
            "rules",
          ],
        ],
        "order/properties-order": [
          [
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index",
            "display",
            "flex",
            "flex-grow",
            "flex-shrink",
            "flex-basis",
            "flex-direction",
            "flex-wrap",
            "justify-content",
            "align-items",
            "align-self",
            "gap",
            "float",
            "clear",
            "overflow",
            "overflow-x",
            "overflow-y",
            "width",
            "min-width",
            "max-width",
            "height",
            "min-height",
            "max-height",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",
            "border",
            "border-width",
            "border-style",
            "border-color",
            "border-radius",
            "outline",
            "outline-width",
            "outline-style",
            "outline-color",
            "font",
            "font-family",
            "font-size",
            "font-weight",
            "line-height",
            "letter-spacing",
            "text-align",
            "text-decoration",
            "text-transform",
            "color",
            "background",
            "background-color",
            "background-image",
            "background-repeat",
            "background-position",
            "background-size",
            "border",
            "border-radius",
            "box-shadow",
            "transition",
            "transform",
            "animation",
            "opacity",
            "cursor",
          ],
          { unspecified: "bottom" },
        ],
      },
    },
  ],
};
