create type rank_enum as ENUM(
	'Mortal I',
	'Mortal II',
	'Mortal III',
	'Mortal IV',
	'Ascendant I',
	'Ascendant II',
	'Ascendant III',
	'Ascendant IV',
	'Seraphic I',
	'Seraphic II',
	'Seraphic III',
	'Seraphic IV',
	'Angelic I',
	'Angelic II',
	'Angelic III',
	'Angelic IV',
	'Divine I',
	'Divine II',
	'Divine III',
	'Divine IV',
	'Celestial I',
	'Celestial II',
	'Celestial III',
	'Celestial IV',
	'Ethereal I',
	'Ethereal II',
	'Ethereal III',
	'Ethereal IV',
	'Transcendent'
);

